version: "3"
services: 
  db: 
    image: postgres
    container_name: local_pgdb
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
  app: 
    image: my-node-app
    ports: 
      - 3000:3000
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: jamielynngleason@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    
  