###
GET http://localhost:3000/personas
###

###
POST http://localhost:3000/createPersona
Content-Type: application/json

{
    "firstName": "Jamie",
    "lastName": "Gleason",
    "latitude": 2.0365,
    "longitude": 1.0365
}
###